# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc0ab5fd22201b12a76af65efd7add410d8fc0292370e1e5db3f0628b0b4b1dec85563acc96d930b7b3f9a0531181c90f67b2f5159f19ebf268a4c665b97c151

test:
  secret_key_base: a0c640648ebd480348e769d677256cf8934050b3334a615fb671d3a33e32558dd394f74b237023da9b3e6864502300de60f7e25296f01da2461dc0f83cbfe207

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
